# -*- coding: utf-8 -*-
"""Test VisDat.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1A8go8V6hCa81W1KWo25JHFI7xpap-33J
"""

import pandas as pd
from bokeh.io import curdoc
from bokeh.plotting import figure
from bokeh.models import HoverTool, ColumnDataSource
from bokeh.models import CategoricalColorMapper
from bokeh.palettes import Spectral6
from bokeh.layouts import widgetbox, row, gridplot
from bokeh.models import Slider, Select

data = pd.read_csv("./data/master.csv")
data.rename(columns={'year' : 'Tahun', 'country' : 'Negara',
                     'sex' : 'Jenis_Kelamin',
                     'age' : 'Umur',
                     'suicides_no' : 'Total_Bunuh_Diri',
                     'population' : 'Populasi',
                     'gdp_per_capita ($)' : 'Pendapatan_per_Kapita',
                     'generation' : 'Generasi'}, inplace = True)
data.rename(columns={data.columns[9]: "GDP_Tahunan" }, inplace = True)
data = data.drop(data.columns[[6,7,8]], axis=1)  
data.columns = data.columns.astype(str)

# Konversi Tipe Data ke int/float/str
# Negara
data.Negara = data.Negara.astype(str)

# Tahun
data.Tahun = data.Tahun.astype(int)

# Jenis Kelamin
data.Jenis_Kelamin = data.Jenis_Kelamin.astype(str)

# Umur
data.Umur = data.Umur.astype(str)

# Total Bunuh Diri
data.Total_Bunuh_Diri = data.Total_Bunuh_Diri.astype(int)

# Populasi
data.Populasi = data.Populasi.astype(int)

# GDP Tahunan
data[data.columns[6]] = data[data.columns[6]].replace('[\,]', '', regex=True).astype(float)

# Pendapatan per Kapita
data.Pendapatan_per_Kapita = data.Pendapatan_per_Kapita.astype(int)

# Generasi
data.Generasi = data.Generasi.astype(str)

#Filter Nilai Bunuh Diri yang = 0
data = data[data['Total_Bunuh_Diri'] > 0]
data.drop_duplicates(inplace = True)
data.dropna(how="any",inplace = True)

data.set_index('Tahun', inplace=True)
data.sort_index(inplace = True)

# Make a list of the unique values from the Generasi
gen_list = data.Generasi.unique().tolist()

# Make a color mapper: color_mapper
color_mapper = CategoricalColorMapper(factors=gen_list, palette=Spectral6)

# Make the ColumnDataSource: source
source = ColumnDataSource(data={
    'x': data.loc[1985].Total_Bunuh_Diri,
    'y': data.loc[1985].Populasi,
    'Negara': data.loc[1985].Negara,
    'Jenis_Kelamin': data.loc[1985].Jenis_Kelamin,
    'Umur': data.loc[1985].Umur,
    'Generasi': data.loc[1985].Generasi,
    })

# Create the figure: plot
plot = figure(title='1985', x_axis_label='Data Kordinat X', y_axis_label='Data Kordinat Y',
              tools=[HoverTool(tooltips = [("Negara : ","@Negara"),
                                           ("Jenis Kelamin : ","@Jenis_Kelamin"),
                                           ("Rentang Usia : ","@Umur")], mode="hline")])

# Add a circle glyph to the figure p
plot.circle(x='x', y='y', source=source, fill_alpha=0.8,
           color=dict(field='Generasi', transform=color_mapper), legend='Generasi')

# Set the legend and axis attributes
plot.legend.location = 'top_left'

# Define the callback function: update_plot
def update_plot(attr, old, new):
    # set the `yr` name to `slider.value` and `source.data = new_data`
    yr = slider.value
    x = x_select.value
    y = y_select.value
    # Label axes of plot
    plot.xaxis.axis_label = x
    plot.yaxis.axis_label = y
    # new data
    new_data = dict(
    'x': data.loc[yr][x],
    'y': data.loc[yr][y],
    'Negara': data.loc[yr].Negara,
    'Jenis_Kelamin': data.loc[yr].Jenis_Kelamin,
    'Umur': data.loc[yr].Umur,
    'Generasi': data.loc[yr].Generasi,
    )
    source.data = new_data
    
    # Add title to figure: plot.title.text
    plot.title.text = 'Data Perbandingan Tahun' % yr

# Make a slider object: slider
slider = Slider(start=1985, end=2016, step=1, value=1985, title='Tahun')
slider.on_change('value',update_plot)

# Make dropdown menu for x and y axis
# Create a dropdown Select widget for the x data: x_select
x_select = Select(
    options=['Total_Bunuh_Diri', 'Populasi', 'GDP_Tahunan', 'Pendapatan_per_Kapita'],
    value='Total_Bunuh_Diri',
    title='x-axis data'
)
# Attach the update_plot callback to the 'value' property of x_select
x_select.on_change('value', update_plot)

# Create a dropdown Select widget for the y data: y_select
y_select = Select(
    options=['Total_Bunuh_Diri', 'Populasi', 'GDP_Tahunan', 'Pendapatan_per_Kapita'],
    value='Populasi',
    title='y-axis data'
)
# Attach the update_plot callback to the 'value' property of y_select
y_select.on_change('value', update_plot)
    
# Create layout and add to current document
layout = row(widgetbox(slider, x_select, y_select), plot)
curdoc().add_root(layout)
